### ISSUE TITLE
DSValueNode showing value of last updated child

### ISSUE THREAD

**Issue by tishma** [iot-dsa-v2/sdk-dslink-java-v2#161]
Hi @a-hansen,

Pls clarify if I'm doing something wrong, or this might be a sdk bug?

I'm implementing `DSValueNode`. I have two child values called:
`"normal-value"` and `"effective-value"`. I've implemented `getValueChild` like this;
```
   @Override
    public DSInfo<DSIValue> getValueChild() {
        return effectiveValue;
    }
```
I would expect my `DSValueNode` to always display `effectiveValue` child's value.
However, I'm experiencing the behaviour of always showing the value of last changed child.

After some debugging, I've realized this line is being executed (hence updating parent's value) upon either of child nodes being set:
https://github.com/iot-dsa-v2/sdk-dslink-java-v2/blob/7292169f41200349da4ffa3716374b6d1e96a90e/dslink-v2/src/main/java/com/acuity/iot/dsa/dslink/protocol/responder/DSInboundSet.java#L72

**Comment by a-hansen** [comment]
Thanks for digging in, I'll take a look.

**Comment by a-hansen** [comment]
Try overriding onSet(DSIValue) to write to the proper child.

**Comment by tishma** [comment]
LOL It's the other direction - I was complaining that both children are affecting parent, but 'overriding onSet' actually helped me come to doing this in parent node class:
```
    @Override
    public void onSet(DSInfo info, DSIValue value) {
        if (info != getValueChild()) return;
        super.onSet(info, value);
    }```
Looking good so far.

**Comment by a-hansen** [comment]
onSet(DSIValue) isn't being called?

**Comment by tishma** [comment]
No, it's other way round. I'm setting the child, and that triggers `parent.onSet(DSInfo info, DSIValue value)` regardless if child is value child or not. My fix seems to work for me, and I'm happy with it. Still, I'm wondering if my assumption of 'value child' concept is correct - I would say it should work two-way (set parent - child gets set, set child - parent gets set). What do you say?

**Comment by a-hansen** [comment]
You can also reimplement DSValueNode (just have your DSNode implement DIValue), it's really a convenience.  If you're trying to use two different values to represent the parent at different times, that's a highly specialized case.  If you don't want people setting the children directly, set the private flag on their DSInfo object.

**Comment by tishma** [comment]
Hey! LOL Is it me, or you are misreading my initial post? I just wanted to have a single child (valueChild) mirror what's displayed as parent's value (irrelevant for the issue, but I only want to set the parent's value by invoking `set` on that child, and never on parent). However, invoking `set` on another child also modifies my parent display which is completely undesired effect.

**Comment by a-hansen** [comment]
It's a bug, I see it.

**Comment by a-hansen** [comment]
Can you test this branch aaron191011-fixEventsOnDSValueNode

Also note that setting the value on the value node was broken as well, and if you don't want that behavior, mark it as readonly on the info in it's parent.

**Comment by a-hansen** [comment]
0.71.0 Released
