### ISSUE TITLE
DSBool action parameter editor

### ISSUE THREAD

**Issue by tishma** [iot-dsa-v2/sdk-dslink-java-v2#167]
@a-hansen Somewhere between `0.70.5` and `0.70.7`, I've lost flip-switch as boolean action parameter editor.
I am expecting the editor to default to flip-switch (or whatever is the correct name for it) to reflect the type of the second parameter in `addParameter`. E.g.
`addParameter("override-to-value", DSBool.TRUE, "");` since `0.70.7`, and including `0.71.0` is rendering as text input field.

**Comment by a-hansen** [comment]
Yikes.  I made a lot of typing related changes, this is definitely a bug.  It's my priority now.
