### ISSUE TITLE
ClassCastException converting to int

### ISSUE THREAD

**Issue by tishma** [iot-dsa-v2/sdk-dslink-java-v2#187]
Reading a value from a BACNet point, an integer per device specs. For whatever reason, when calling `value.toInt()` I'm getting `java.lang.ClassCastException: org.iot.dsa.node.DSString not int`.

Looking into the sources/comments - it says out that `Strings will attempt to parseRequest the numeric which may result in a parseRequest exception.`, but no trace of implementation in `DSString` class.

My problem definitely is somewhere else, but it'd be great if `DSString` actually attempted parsing, and included the value that failed to parse into the exception message.

**Comment by a-hansen** [comment]
Fixed in 0.78.0
